# Generated by Django 3.2.13 on 2022-07-02 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0002_auto_20220702_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporthistoryprediction',
            name='prediction_high',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='reporthistoryprediction',
            name='prediction_low',
            field=models.FloatField(),
        ),
    ]
